import { Html } from 'next/document';
import Head from 'next/head';
import config_yml from '@/config/config.yaml';
import './defaultStyles/defaultStyles.css';

function App({ Component, pageProps }) {
  const config = config_yml ? config_yml : {};
  console.log('config', config);
  return (
    <>
      <Head>
        <title>{config.site_title ? config.site_title : 'Harugo App'}</title>
        <meta
          name="description"
          content={
            config.site_description
              ? config.site_description
              : 'Generated by Harugo Next.js SSG'
          }
        />
      </Head>
      <Component config={config} {...pageProps} />
    </>
  );
}

export default App;
