# --- Website settings start ---
site_title: devnyxie
site_description: devnyxie website's description.
# --- Website settings end ---

# --- User start ---
user:
  name: Tim
  position: software engineer
  bio: |
    I'm a software engineer based in Warsaw, Poland. I'm passionate about mostly everything related to development. I'm also a big fan of open-source and I'm always looking for new opportunities to contribute to the community.
  profile_picture: /profile.jpg
  email: test@gmail.com
# --- User end ---

# --- Pages start ---
pages:
  - name: Home
    path: /
# --- Pages end ---

# --- Social start ---
# --- Social end ---

# --- Components Settings start ---
# --- Components Settings end ---

